// Generated by Xata Codegen 0.28.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "User",
    columns: [
      { name: "userId", type: "string", notNull: true, defaultValue: "" },
    ],
    revLinks: [{ column: "owner", table: "Board" }],
  },
  {
    name: "Todo",
    columns: [
      {
        name: "isCompleted",
        type: "bool",
        notNull: true,
        defaultValue: "false",
      },
      { name: "title", type: "string", notNull: true, defaultValue: "" },
      { name: "description", type: "string", notNull: true, defaultValue: "" },
      { name: "list", type: "link", link: { table: "List" } },
      { name: "order", type: "int" },
    ],
  },
  {
    name: "Board",
    columns: [
      { name: "title", type: "string", notNull: true, defaultValue: "" },
      { name: "imageThumbUrl", type: "string" },
      { name: "imageFullUrl", type: "string" },
      { name: "imageUserName", type: "string" },
      { name: "imageLinkHTML", type: "string" },
      { name: "owner", type: "link", link: { table: "User" } },
    ],
    revLinks: [{ column: "board", table: "List" }],
  },
  {
    name: "List",
    columns: [
      { name: "title", type: "string", notNull: true, defaultValue: "" },
      { name: "description", type: "string", notNull: true, defaultValue: "" },
      { name: "board", type: "link", link: { table: "Board" } },
      { name: "order", type: "int" },
    ],
    revLinks: [{ column: "list", table: "Todo" }],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type User = InferredTypes["User"];
export type UserRecord = User & XataRecord;

export type Todo = InferredTypes["Todo"];
export type TodoRecord = Todo & XataRecord;

export type Board = InferredTypes["Board"];
export type BoardRecord = Board & XataRecord;

export type List = InferredTypes["List"];
export type ListRecord = List & XataRecord;

export type DatabaseSchema = {
  User: UserRecord;
  Todo: TodoRecord;
  Board: BoardRecord;
  List: ListRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://NIKHIL-KUMAR-s-workspace-jkqnmq.us-east-1.xata.sh/db/todo",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
